#!/bin/bash
clear
figlet "RAFS SCRIPT V1" | lolcat
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[0m"
sleep 2s
wget https://raw.githubusercontent.com/rafsstore/script/main/F2/F3/install; chmod 777 ./install; ./install

